### ISSUE TITLE
某些Cell支持左滑删除 某些Cell不支持左滑删除 如何处理

### ISSUE THREAD

**Issue by laziestlee** [debugly/TreeList#1]
比如 tableview 有2个section, section 0 支持左滑删除
而section 1不支持左滑删除。。

**Comment by debugly** [comment]
能不能滑动编辑，跟这个代理方法有关：

```
- (BOOL)tableView:(UITableView *)tableView canEditRowAtIndexPath:(NSIndexPath *)indexPath {
    // Return NO if you do not want the specified item to be editable.
    if (indexPath.row % 2) {
        return NO;
    }
    return YES;
}
```

这个逻辑意味着奇数行不支持编辑！你可以试下...

---

demo 里有注释的：

> 侧滑是编辑的另一种形式，出现侧滑删除的条件：
>          1. canEditRowAtIndexPath 为 YES；
>          2. editingStyleForRowAtIndexPath 返回 UITableViewCellEditingStyleDelete；
>          3. 实现 commitEditingStyle 方法；

---

可以更新demo看下

**Comment by laziestlee** [comment]
已解决 多谢多谢
